name: gmutils_flutter
description: "gmutils_flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter

  package_info_plus: ^8.0.2

  firebase_analytics: ^11.4.5
  firebase_core_platform_interface: ^5.4.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_remote_config: ^5.4.3
  googleapis_auth: ^1.6.0

  http: ^1.1.0

  uuid: ^4.0.0
#  crypto: ^3.0.1
  crypto: ^3.0.5

  sqflite:
  path: ^1.8.2

#  path_provider: ^2.0.11
  path_provider: ^2.1.4
#  shared_preferences: ^2.0.7
  shared_preferences: ^2.3.2
  encrypt: ^5.0.1

  external_app_launcher: ^4.0.0
  url_launcher: ^6.0.17
#  app_links: ^3.2.0
  app_links: ^6.1.4
#  share_plus: ^7.0.0
  share_plus: ^10.0.0

  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^18.0.1

  webview_flutter: ^4.8.0
  device_info_plus: ^10.1.2

#  image_picker: ^0.8.6+1
  image_picker: ^1.1.2
  image: ^4.0.12
#  image_cropper: ^5.0.0
  image_cropper: ^8.0.2

  file_picker: ^8.0.0+1
#  file_picker: ^8.1.2

  record: ^5.1.2
  audioplayers: ^6.0.0
  video_player: ^2.9.1
  open_file_plus: ^3.4.1+1
  flutter_widget_from_html: ^0.15.1

#  device_info_plus: ^10.1.1

  #async_zip: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^3.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/keys/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
