name: gmutils_flutter
description: "gmutils_flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter

  package_info_plus: ^8.3.0

  firebase_analytics: ^11.5.2
  firebase_core_platform_interface: ^6.0.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_database: ^11.3.9
#  firebase_auth: ^5.5.2
#  firebase_storage: ^12.4.5
  firebase_remote_config: ^5.4.7
#  googleapis_auth: ^1.6.0

  http: ^1.1.0

  uuid: ^4.5.1
  crypto: ^3.0.6

  sqflite:
  path: ^1.9.0

  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  encrypt: ^5.0.1

  external_app_launcher: ^4.0.3
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  share_plus: ^10.1.4

  flutter_linkify: ^6.0.0

  flutter_local_notifications: ^19.0.0

  device_info_plus: ^10.1.2
  webview_flutter: ^4.10.0

  image_picker: ^1.1.2
  image: ^4.5.4
  image_cropper: ^9.1.0
  #async_zip: ^0.1.0

  file_picker: ^10.1.9

  lucide_icons: ^0.257.0

  qr_flutter: ^4.1.0
  totp: ^0.1.0
  geolocator: ^14.0.2
  video_player: ^2.10.0


  firebase_analytics: ^11.4.5
  firebase_core_platform_interface: ^5.4.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_remote_config: ^5.4.3
  googleapis_auth: ^1.6.0

  flutter_local_notifications: ^18.0.1
  
  http: ^1.1.0

  uuid: ^4.0.0
  crypto: ^3.0.5
  encrypt: ^5.0.1

  sqflite:
      
  path: ^1.8.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  
  external_app_launcher: ^4.0.0
  url_launcher: ^6.0.17
  app_links: ^6.1.4
  share_plus: ^10.0.0

  flutter_linkify: ^6.0.0
  
  webview_flutter: ^4.8.0
  
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2

  image_picker: ^1.1.2
  image: ^4.0.12
  image_cropper: ^8.0.2

  file_picker: ^8.0.0+1

  record: ^5.1.2
  audioplayers: ^6.0.0
  video_player: ^2.9.1
  open_file_plus: ^3.4.1+1
  flutter_widget_from_html: ^0.15.1

#  device_info_plus: ^10.1.1

  #async_zip: ^0.1.0

  totp: ^0.1.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/keys/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
