name: pallora
description: Keep your eyes on your lovers

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter

  package_info_plus: ^4.0.0

  firebase_analytics: ^10.6.1
  firebase_core_platform_interface: ^5.0.0
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  firebase_database: ^10.3.1
  firebase_auth: ^4.11.1
  firebase_storage: ^11.3.1

  http: ^1.1.0

  uuid: ^4.0.0
  crypto: ^3.0.1

  sqflite:
  path: ^1.8.2

  path_provider: ^2.0.11
  shared_preferences: ^2.0.7
  encrypt: ^5.0.1

  external_app_launcher: ^3.1.0
  url_launcher: ^6.0.17
  app_links: ^3.2.0
  share_plus: ^7.0.0

  flutter_rating_bar: ^4.0.0
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^14.0.0+1

  webview_flutter: ^4.0.2
  #device_info_plus: ^9.0.0

  image_picker: ^0.8.6+1
  image: ^4.0.12
  image_cropper: ^5.0.0
  #async_zip: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf

    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-VariableFont_wght.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rajdhani-Light.ttf
          weight: 300
        - asset: assets/fonts/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
          weight: 600
