# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GMUtils' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMUtils
pod 'Alamofire', '~> 5.2'
pod 'SideMenu', '~> 6.0'
pod 'Kingfisher', '~> 5.0'
# pod 'SwiftOTP'
# pod 'SwiftKeychainWrapper'
# pod 'LanguageManager-iOS'
# pod 'Firebase/Analytics'
# pod 'Firebase/Messaging'
# pod 'Firebase/RemoteConfig'
end

target 'GMUtilsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMUtilsExample

end
