# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GMUtilsIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMUtilsIOS
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 5.0'
pod 'LanguageManager-iOS'
pod 'SwiftKeychainWrapper'

  target 'GMUtilsIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GMUtilsIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
